baseURL = "https://pwhau.github.io" #一定要用https，github強制安全措施
languageCode = "zh-tw" #語言
title = "P.W. 象牙塔" #標題
paginate = 3 #分頁每頁記錄數
DisqusShortname = "P.W." #評論顯示的名稱
Copyright = "All rights reserved - 2020" #版權聲明
# canonifyurls = true

[params]
  description = "We are all in the gutter, but some of us are looking at the stars." #加段提升逼格的副标题
  cover = "images/cover.jpg" #自己找的博客封面，要够大够酷
  author = "P.W." #文章作者
  authorlocation = "Taipei, Taiwan" #作者位置
#   # authorwebsite = "https://brent-li.github.io/" #作者站点
#   #bio= "京东|高级软件工程师" #作者简介
#   #logo = "images/Einstan.jpg" #作者头像
#   #googleAnalyticsUserID = "UA-79101-12" 
#   # Optional RSS-Link, if not provided it defaults to the standard index.xml
#   #RSSLink = "http://feeds.feedburner.com/..."
#   # githubName = "Brent-Li" #github用户名
#   #twitterName = "vjeantet" 
#   # facebookName = ""
#   # linkedinName = "zifeng" #LinkedIn用户名
#   # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
#   # hideHUGOSupport = false #是否显示Hugo水印
#   # [params.social]
#     # linkedin = "https://cn.linkedin.com/in/zifeng"
	
[[menu.main]] #页面菜单参数
  name = "象牙塔"
  weight = -120
  identifier = "blog"
  url = "/posts"

[[menu.main]]
  name = "關於我"
  weight = -110
  identifier = "about"
  url = "/about"

[[menu.main]]
  name = "攝影"
  weight = -110
  identifier = "photography"
  url = "/photography"

[[menu.main]]
  name = "UI"
  weight = -110
  identifier = "UI"
  url = "/UI"

[[menu.main]]
  name = "website"
  weight = -110
  identifier = "website"
  url = "/website"